/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
import ts from 'typescript';        /* moduleSpecifier */ ts.factory.create    //
    // This operation is load-bearing in g3 as some imported modules contain special metadata
    // generated by clutz, which tsickle uses to transform imports and refe    // TODO(alxhub): add a test for this when tsickle is updated externally to depend on this
    // behavior.
    ts.setOriginalNode(i.qualifier, decl);    return decl;
  });  // Filter out the existing imports and the source file body. All new statements
  // will be inserted between them.  const body = sf.statements.filter(stmt => !isImportStatement(stmt));
  // Prepend imports if needed.
  if (addedImports.length > 0) {    // for @fileoverview Closure annotation. If there is no @fileoverview annotations, this
    /    return ts.factory.updateSourceFile(sf, ts.factory.createNodeArray([
      fileoverviewAnchorStmt, ...existingImports, ...addedImports, ...extra  }  return sf;
}function isImportStatement(stmt: ts.Statement): boolean {
  return ts.isImportDeclaration(stmt) || t}
